language: java
jdk:
  - openjdk7
install: "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dcobertura.skip=true -B -V"
before_script: "git clone -b travis `git config --get remote.origin.url` target/travis"
script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn deploy --settings target/travis/settings.xml -B -V || false'
  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && mvn install --settings target/travis/settings.xml -B -V || false'
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn site --settings target/travis/settings.xml -B -V || false'
branches:
  except:
    - travis
    - gh-pages
cache:
  directories:
  - $HOME/.m2
env:
  global:
    - secure: "FE0dNQmTW1IAxLCcJucCUzsz0rxqNJWGRmOKCAX6SiusEVqJ4c4GboKsPyASFKrAO79hfJnAtkCqPqJYekedDQ9hw9eAwK5VdY68A8uD8TTAlXC8D6GOXGwzfUMk9C1md2dfjOoGBGFv+/kHjlL4sfRKIwmb4ZdFY6G4pXZPf7c="
    - secure: "e3bJJw9Jl0del0LqHHGcr1MVb6k6npu5wawKULQdwgfudDU1Wp8xlA4xS4TcDxBJWzehzWoIsh/sGlxjNoKN+wBbEGCQ9Rwc5evpfGM1atPrsufVF0bEbsFF+5nPd9tUBMubNDcauSd6xuSmJxuYw4AVToqwdFFrFbxHpxvCCCo="
